name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=eu-north-1" >> $GITHUB_ENV
        echo "POSTGIS_DBNAME=${{ secrets.POSTGIS_DBNAME }}" >> $GITHUB_ENV
        echo "POSTGIS_USERNAME=${{ secrets.POSTGIS_USERNAME }}" >> $GITHUB_ENV
        echo "POSTGIS_PASSWORD=${{ secrets.POSTGIS_PASSWORD }}" >> $GITHUB_ENV
        echo "POSTGIS_HOST=${{ secrets.POSTGIS_HOST }}" >> $GITHUB_ENV

    - name: Zip the deployment package
      run: |
        mkdir package
        pip3.11 install --target ./package -r requirements.txt
        cp -r app package/
        cp run.py package/
        cp .env package/
        cd package
        zip -r ../deployment_package.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to AWS Lambda
      run: |
        terraform init
        terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
          -var="postgis_dbname=${{ secrets.POSTGIS_DBNAME }}" \
          -var="postgis_username=${{ secrets.POSTGIS_USERNAME }}" \
          -var="postgis_password=${{ secrets.POSTGIS_PASSWORD }}" \
          -var="postgis_host=${{ secrets.POSTGIS_HOST }}" \
          -var="deployment_s3_bucket_name=${{ secrets.DEPLOYMENT_S3_BUCKET_NAME }}" \
          -var="aws_secret_name=${{ secrets.AWS_SECRET_NAME }}" \
          -var="aws_vpc_id=${{ secrets.AWS_VPC_ID }}" \
          -var="aws_subnet_ids=${{ secrets.AWS_SUBNET_IDS }}" \
          -var="rds_sg_id=${{ secrets.AWS_RDS_SG_ID }}"
        